In [16]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests

import re

In [3]:
company_df=pd.read_csv('company.csv')

In [4]:
company=company_df['Symbol']

In [5]:
check=company.iloc[1:9]

In [21]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage=requests.get('https://ticker.finology.in/company/TCS',headers=headers).text

In [70]:
soup=BeautifulSoup(webpage,'lxml')
a=soup.find('div',id="companyessentials")

b=a.find_all('div',class_="col-6 col-md-4 compess")[0:-2]

In [65]:
b[0:-1]

[<div class="col-6 col-md-4 compess">
 <small>Market Cap<span class="infolink" data-tooltip="tooltip" title="Market capitalization is the aggregate valuation of the company based on its current share price and the total number of outstanding shares."><i class="fas fa-info-circle"></i></span></small>
 <p>
                                 ₹ <span class="Number">1281088.77</span> Cr.
                             </p>
 </div>,
 <div class="col-6 col-md-4 compess">
 <small>
 <span id="mainContent_lblEPCASA">Enterprise Value</span>
 <span class="infolink" data-tooltip="tooltip" title="it measures companys total value, which includes market capitalization, debt and excludes cash."><i class="fas fa-info-circle"></i></span>
 </small>
 <p>
 <span id="mainContent_ltrlEntValue">₹ <span class="Number">1267396.77</span> Cr.</span>
 </p>
 </div>,
 <div class="col-6 col-md-4 compess">
 <small>No. of Shares<span class="infolink" data-tooltip="tooltip" title="It shows the number of shares outstanding in the company."><i class="fas fa-info-circle"></i></span></small>
 <p>
 <span class="Number">365.91</span> Cr.
                             </p>
 </div>,
 <div class="col-6 col-md-4 compess">
 <small>P/E<span class="infolink" data-tooltip="tooltip" title="It is a valuation parameter that measures the company's current share price relative to its per-share earnings. Generally, high P/E is Overvalued &amp; low P/E is Undervalued."><i class="fas fa-info-circle"></i></span></small>
 <p>
                                 32.76
                             </p>
 </div>,
 <div class="col-6 col-md-4 compess">
 <small>P/B<span class="infolink" data-tooltip="tooltip" title="It shows the relationship between the current price and the book value of each share. A lower P/B ratio can mean that the stock is undervalued."><i class="fas fa-info-circle"></i></span></small>
 <p>
                                 13.55
                             </p>
 </div>,
 <div class="col-6 col-md-4 compess">
 <small>Face Value<span class="infolink" data-tooltip="tooltip" title="Value of a security, as stated by its issuer. It has no relation with market price of the stock."><i class="fas fa-info-circle"></i></span></small>
 <p>
                                 ₹ 1
                             </p>
 </div>,
 <div class="col-6 col-md-4 compess">
 <small>Div. Yield<span class="infolink" data-tooltip="tooltip" title="It measures the amount of cash dividends distributed to equity shareholders relative to the market value per share."><i class="fas fa-info-circle"></i></span></small>
 <p>
                                 1.23 %
                             </p>
 </div>,
 <div class="col-6 col-md-4 compess">
 <small>Book Value (TTM)<span class="infolink" data-tooltip="tooltip" title="It calculates the per share value of a company based on its equity available to common shareholders."><i class="fas fa-info-circle"></i></span></small>
 <p>
                                 ₹
                                     <span class="Number">258.39</span>
 </p>
 </div>,
 <div class="col-6 col-md-4 compess">
 <small>
 <span id="mainContent_lblCashNPI">CASH</span>
 <span class="infolink" data-tooltip="tooltip" title="The cash balance at the end of year after paying out dividends and expenses."><i class="fas fa-info-circle"></i></span>
 </small>
 <p>
 <span id="mainContent_ltrlCash">₹ <span class="Number">13692</span> Cr.</span>
 </p>
 </div>,
 <div class="col-6 col-md-4 compess">
 <small>
 <span id="mainContent_lblDEBTCostToIncome">DEBT</span>
 <span class="infolink" data-tooltip="tooltip" title="It is the sum of all short term and long term debts taken by the company."><i class="fas fa-info-circle"></i></span>
 </small>
 <p>
 <span id="mainContent_ltrlDebt">₹ <span class="Number">0</span> Cr.</span>
 </p>
 </div>,
 <div class="col-6 col-md-4 compess">
 <small>Promoter Holding<span class="infolink" data-tooltip="tooltip" title="The % of shares that are held by the promoters of a company."><i class="fas fa-info-circle"></i></span></small>
 <p>
                                 72.3 %
                             </p>
 </div>,
 <div class="col-6 col-md-4 compess">
 <small>EPS (TTM)<span class="infolink" data-tooltip="tooltip" title="It is the profit allocated to each outstanding share of common stock."><i class="fas fa-info-circle"></i></span></small>
 <p>
                                 ₹
                                     <span class="Number">106.86</span>
 </p>
 </div>,
 <div class="col-6 col-md-4 compess">
 <small>
 <span id="mainContent_lblSalesGrowthorCasa">Sales Growth</span>
 <span class="infolink" data-tooltip="tooltip" title="It shows the growth in sales revenues over a fixed period of time. Higher the rate, better it is."><i class="fas fa-info-circle"></i></span>
 </small>
 <p>
 <span class="Number">17.93</span>%
                             </p>
 </div>,
 <div class="col-6 col-md-4 compess">
 <small>ROE
                                 <span class="infolink" data-tooltip="tooltip" title="It measures the ability of a firm to generate profits from its shareholders investments in the company."><i class="fas fa-info-circle"></i></span></small>
 <p>
 <span class="Number">50.76</span> %

                             </p>
 </div>,
 <div class="col-6 col-md-4 compess">
 <small>ROCE<span class="infolink" data-tooltip="tooltip" title="It measures how efficiently a company is using its capital employed (Debt &amp; Equity). [Higher is better]  "><i class="fas fa-info-circle"></i></span></small>
 <p>
 <span class="Number">66.74</span>%

                             </p>
 </div>,
 <div class="col-6 col-md-4 compess">
 <small>Profit Growth
                                     <span class="infolink" data-tooltip="tooltip" title="It shows the growth in Net Profit over a fixed period of time. Higher the rate, better it is."><i class="fas fa-info-circle"></i></span></small>
 <p>
 <span class="Number">23.34</span> %

                             </p>
 </div>]

## Main Funtion Test

In [71]:
df=pd.DataFrame()
d={}
for j in b:
    heading=j.find('small').text.strip()
    value=j.find('p').text.strip()
    dic={heading:value,'sombol':i}
    d.update(dic)
    x.append(heading)   
y=pd.DataFrame(d,index=[1])
df=pd.concat([df,y])
df

,Market Cap,sombol,Enterprise Value,No. of Shares,P/E,P/B,Face Value,Div. Yield,Book Value (TTM),CASH,DEBT,Promoter Holding,EPS (TTM),Sales Growth,ROE,ROCE
1,₹ 1281088.77 Cr.,SBIN,₹ 1267396.77 Cr.,365.91 Cr.,32.76,13.55,₹ 1,1.23 %,₹ \r\n 258.39,₹ 13692 Cr.,₹ 0 Cr.,72.3 %,₹ \r\n 106.86,17.93%,50.76 %,66.74%

In [42]:
b[0]

<div class="col-6 col-md-4 compess">
<small>Market Cap<span class="infolink" data-tooltip="tooltip" title="Market capitalization is the aggregate valuation of the company based on its current share price and the total number of outstanding shares."><i class="fas fa-info-circle"></i></span></small>
<p>
                                ₹ <span class="Number">1281088.77</span> Cr.
                            </p>
</div>

## Main funtion

In [76]:
df=pd.DataFrame()
for i in company:
    try:
        url='https://ticker.finology.in/company/{}'.format(i)
        headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
        webpage=requests.get(url,headers=headers,timeout=50).text
        soup=BeautifulSoup(webpage,'lxml')
        a=soup.find('div',id="companyessentials")

        b=a.find_all('div',class_="col-6 col-md-4 compess")[0:-2]

        d={}
        for j in b:
            heading=j.find('small').text.strip()
            value=j.find('p').text.strip()
            dic={heading:value,'sombol':i}
            d.update(dic)  
        y=pd.DataFrame(d,index=[1])
        df=pd.concat([df,y])
    except:
        pass

In [78]:
df.to_csv('indian_stocks.csv')

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1977 entries, 1 to 1
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Market Cap           1977 non-null   object
 1   sombol               1977 non-null   object
 2   Enterprise Value     1795 non-null   object
 3   No. of Shares        1977 non-null   object
 4   P/E                  1977 non-null   object
 5   P/B                  1977 non-null   object
 6   Face Value           1977 non-null   object
 7   Div. Yield           1977 non-null   object
 8   Book Value (TTM)     1977 non-null   object
 9   CASH                 1796 non-null   object
 10  DEBT                 1796 non-null   object
 11  Promoter Holding     1977 non-null   object
 12  EPS (TTM)            1977 non-null   object
 13  Sales Growth         1942 non-null   object
 14  ROE                  1977 non-null   object
 15  ROCE                 1977 non-null   object
 16  CASA %               35 non-null     object
 17  Net Interest Income  35 non-null     object
 18  Cost To Income %     35 non-null     object
 19  CAR %                35 non-null     object
 20  Advances             147 non-null    object
 21  Operating Revenue    146 non-null    object
 22  Net Profit           146 non-null    object
dtypes: object(23)
memory usage: 370.7+ KB

In [3]:
df=pd.read_csv('indian_stocks.csv')

In [10]:
df['Book Value (TTM)']=df['Book Value (TTM)'].apply(lambda x:re.sub('\\r\\n','',x))

In [12]:
df.iloc[0]

Unnamed: 0                                                           1
Market Cap                                            ₹ 1651037.86 Cr.
sombol                                                        RELIANCE
Enterprise Value                                      ₹ 1823886.86 Cr.
No. of Shares                                                676.6 Cr.
P/E                                                              38.15
P/B                                                               3.43
Face Value                                                        ₹ 10
Div. Yield                                                      0.33 %
Book Value (TTM)          ₹                                     711.58
CASH                                                       ₹ 21714 Cr.
DEBT                                                      ₹ 194563 Cr.
Promoter Holding                                               50.49 %
EPS (TTM)              ₹ \r\n                                    63.96
Sales Growth                                                    72.47%
ROE                                                             8.63 %
ROCE                                                             8.21%
CASA %                                                             NaN
Net Interest Income                                                NaN
Cost To Income %                                                   NaN
CAR %                                                              NaN
Advances                                                           NaN
Operating Revenue                                                  NaN
Net Profit                                                         NaN
Name: 0, dtype: object

In [13]:
df['EPS (TTM)']=df['EPS (TTM)'].apply(lambda x:re.sub('\\r\\n','',x))

In [18]:
df

,sombol,Market Cap,Enterprise Value,No. of Shares,P/E,P/B,Face Value,Div. Yield,CASH,DEBT,...,Sales Growth,ROE,ROCE,CASA %,Net Interest Income,Cost To Income %,CAR %,Advances,Operating Revenue,Net Profit
0,RELIANCE,₹ 1651037.86 Cr.,₹ 1823886.86 Cr.,676.6 Cr.,38.15,3.43,₹ 10,0.33%,₹ 21714 Cr.,₹ 194563 Cr.,...,72.47%,8.63%,8.21%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TCS,₹ 1281088.77 Cr.,₹ 1267396.77 Cr.,365.91 Cr.,32.76,13.55,₹ 1,1.23%,₹ 13692 Cr.,₹ 0 Cr.,...,17.93%,50.76%,66.74%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HDFCBANK,₹ 923696.03 Cr.,NaN,557.82 Cr.,21.93,3.45,₹ 1,0.94%,NaN,NaN,...,NaN,16.67%,14.62%,48.17,₹ 72009.59 Cr.,36.88,18.90,NaN,NaN,NaN
3,INFY,₹ 656905.52 Cr.,₹ 644635.52 Cr.,414.77 Cr.,29.14,8.23,₹ 5,1.96%,₹ 12270 Cr.,₹ 0 Cr.,...,20.98%,30.37%,40.65%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ICICIBANK,₹ 602207.21 Cr.,NaN,698.09 Cr.,20.21,3.21,₹ 2,0.58%,NaN,NaN,...,NaN,14.99%,14.01%,48.70,₹ 47466.09 Cr.,40.52,19.16,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1972,TCIFINANCE,₹ 4.63 Cr.,NaN,1.29 Cr.,0.00,0.00,₹ 10,0%,NaN,NaN,...,6.4,0%,0%,NaN,NaN,NaN,NaN,₹ 0 Cr.,₹ 4.53 Cr.,₹ -32.97 Cr.
1973,TECILCHEM,₹ 0 Cr.,₹ 12.01 Cr.,1.9 Cr.,0.00,0.00,₹ 10,0%,₹ 0 Cr.,₹ 12.02 Cr.,...,0%,0%,0%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1974,UNIVAFOODS,0,0,1.43 Cr.,0.00,NaN,0,0%,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1975,VICEROY,₹ 11.45 Cr.,₹ 477.85 Cr.,4.24 Cr.,0.00,0.00,₹ 10,0%,₹ 2.13 Cr.,₹ 468.53 Cr.,...,90.24%,0%,-12.87%,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1976,WSI,₹ 78.82 Cr.,₹ 128.65 Cr.,4.47 Cr.,22.69,0.00,₹ 10,0%,₹ 22.57 Cr.,₹ 72.4 Cr.,...,0%,0%,-1.98%,NaN,NaN,NaN,NaN,NaN,NaN,NaN